Feat/add users and regions crud
romesdev/ozmap-technical-assessment-dev-main pull request #2
Opened 2024-12-10 22:17 UTC by romesdev

# Descrição

- 

# Tipo de mudança

Selecione o tipo de mudança que este PR introduz:

- [ ] 🐛 **Bug fix** (correção de um problema)
- [ ] ✨ **Feature** (nova funcionalidade)
- [ ] ⚙️ **Refactor** (refatoração de código, sem mudanças de comportamento)
- [ ] 🧹 **Chore** (tarefas de manutenção ou ajustes menores)
- [ ] 📖 **Documentação** (alterações ou adições na documentação)
- [ ] 🚀 **CI/CD** (ajustes em pipelines ou workflows de integração e entrega contínua)
- [ ] 🛠️ **Configuração** (configuração de ambiente ou setup inicial)
- [ ] 📝 **Script de deploy** (alterações ou adição de scripts relacionados a deploy)
- [ ] 🔧 **Outros** (descreva abaixo)

# Checklist

Certifique-se de que seu PR atenda aos critérios abaixo:

- [ ] Código segue os padrões definidos no projeto.
- [ ] Todos os testes foram executados e aprovados.
- [ ] Documentação atualizada (se necessário).
- [ ] Código revisado e testado localmente.
- [ ] Não há conflitos com a branch `master` ou `develop`.

# Como testar?

# Capturas de tela (opcional)

# Card/Issue relacionado (se aplicável)

2024-12-19 20:11 UTC, bedretchukdevoz requested changes

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/controllers/region.controller.ts
> +      return res.status(201).json(response);
Status Code hardcodado, por que não fez algo mais estruturado para os códigos http

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/controllers/region.controller.ts
> +        .json({ message: "Error to create a region", details: error });
melhor tratamento de erro
evitar try catch repetitivos, usar biblioteca / middleware para tratamento dos erros.

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/controllers/region.controller.ts
> +      const response = await this.regionService.get();
por que não passar como parâmetro dados de paginação?

implementar paginação

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/controllers/region.controller.ts
> +      const query = {
melhorar tipagem.

não sei se precisa typecast, o request aceita tipos caso necessário

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/controllers/region.controller.ts
> +      const response = await this.regionService.getByPoint(query);
nomenclatura da variável poderia ser mais clara. nesse caso o serviço recebe "coords" ou "coordinates"

NIT com melhoria de padrão de nomenclatura

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/controllers/region.controller.ts
> +        .json({ message: "Error to create a region", details: error });
outra coisa é que isso aqui não chama o middleware de tratamento de erro, então a aplicação não está efetivamente utilizando o errorHandlerMiddleware

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/repositories/region.repository.ts
> +    const region = this.model.findByIdAndUpdate(id, updateData, {
você diz que está retornando a region, mas aqui só retorna a promise da region
padrão de nomenclatura.

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/middlewares/validateQuery.middleware.ts
> +    } catch (error) {
em caso de erro você não está chamando seu middleware de tratamento de erro

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/services/region.service.spec.ts
> +import { describe, it, expect, vi, beforeEach } from 'vitest';
Por que não usar mongo session para preservar o estado do banco após cada run de testes?

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/services/region.service.ts
> +            code: "USER_NOT_FOUND",
porque retornar esse code específico?

2024-12-19 20:11 UTC, bedretchukdevoz commented on src/services/region.service.ts
> +  async get(): Promise<Result<Region[]>> {
seria interessante ter a sessão como parametro, para caso seja necessário acessar um documento que a transaction ainda não terminou

2024-12-23 20:40 UTC, romesdev commented on src/services/region.service.spec.ts
> +import { describe, it, expect, vi, beforeEach } from 'vitest';
Nos meus testes, eu procurei todo o comportamento (operações) do banco para não alterar o estado do banco. 

Por isso, uso `vi.fn()` em cada método do repositório. Ele simula os métodos para mim.

2024-12-23 20:41 UTC, romesdev commented on src/services/region.service.ts
> +  async get(): Promise<Result<Region[]>> {
Adicionei session como parâmetro nas operações do banco que não tinha. Fiz isso do service para o repositório. 

Pois, é o service que é responsável por controlar esse fluxo com múltiplas operações e repositórios.

2024-12-23 20:43 UTC, romesdev commented on src/repositories/region.repository.ts
> +    const region = this.model.findByIdAndUpdate(id, updateData, {
Ajustado. Faltou await para aguardar a operação ser concluída para retornar o resultado. 

Pode até fazer sentido utilizar uma nomenclatura de `response` ou `result `para os valores retornados pelo banco ou apis.

2024-12-23 20:44 UTC, romesdev commented on src/controllers/region.controller.ts
> +      const response = await this.regionService.getByPoint(query);
Modifiquei para `coordinates` para melhorar o entendimento.

2024-12-23 20:45 UTC, romesdev commented on src/controllers/region.controller.ts
> +      const query = {
Bom ponto.

Nesse caso, eu tô usando meus middlewares para validação para checar o body e os query params. Inclusive, eles fazem coerção de tipo para entender se o valor é válido.

2024-12-23 20:46 UTC, romesdev commented on src/controllers/region.controller.ts
> +      const response = await this.regionService.get();
Paginação implementada para as buscas. ✅

2024-12-23 20:47 UTC, romesdev commented on src/controllers/region.controller.ts
> +      return res.status(201).json(response);
Bem apontado. 

Agora, estamos usando constantes. Eu já tinha criado anteriormente. Só que acabei esquecendo de utilizar em todo o código.

2024-12-23 21:22 UTC, romesdev commented on src/controllers/region.controller.ts
> +        .json({ message: "Error to create a region", details: error });
De fato. Tem uma boa quantidade de `try/catch` na aplicação. Procurei melhorar isso, finalmente, colocando mais responsabilidades para o meu `middleware` para erros inesperados.

2024-12-23 21:23 UTC, romesdev commented on src/middlewares/validateQuery.middleware.ts
> +    } catch (error) {
Ajustado. Para lidar com o erro quando ele não for um `ZodError`.

2024-12-23 21:25 UTC, romesdev commented on src/services/region.service.ts
> +            code: "USER_NOT_FOUND",
Acho que aqui em uma fiz uma redundância na mensagem e no código. Aqui, eu já poderia ter informado o http status code para o controller resolver mais acima, caso necessário.

2025-04-10 13:48 UTC, bedretchukdevoz approved these changes

2025-04-29 20:43 UTC, merged